import type { VoiceLine } from '../../../../../content/site.ts';

/**
 * Generated by `pnpm --filter @inrp2p/web voice:clips` from the clips beside it — do not edit by hand.
 * PLACEHOLDER clips, rendered with the macOS "Daniel" voice: replace with recordings before launch.
 *
 * `duration` is in seconds; `peaks` are the stressed syllables, seconds from the start with their loudness;
 * `level` is loudness 0–1 at 50 frames a second.
 */
export interface ClipMeasurement {
  readonly duration: number;
  readonly peaks: readonly { readonly at: number; readonly level: number }[];
  readonly level: readonly number[];
}

export const LEVEL_RATE = 50;

export const INTERIM = true;

export const CLIP_MEASUREMENTS: Record<VoiceLine, ClipMeasurement> = {
  ready: {
    duration: 1.151,
    peaks: [{at:0.1,level:0.99},{at:0.26,level:0.96},{at:0.44,level:0.98},{at:0.66,level:0.96}],
    level: [0.27, 0.62, 0.73, 0.81, 0.97, 1, 0.97, 0.96, 0.92, 0.73, 0.68, 0.88, 0.95, 0.97, 0.96, 0.95, 0.96, 0.92, 0.86, 0.8, 0.87, 0.99, 0.98, 0.97, 0.9, 0.86, 0.83, 0.83, 0.87, 0.86, 0.87, 0.91, 0.95, 0.97, 0.96, 0.93, 0.94, 0.91, 0.87, 0.8, 0.81, 0.7, 0.63, 0.68, 0.57, 0.55, 0.61, 0.55, 0.52, 0.51, 0.58, 0.49, 0.48, 0.46, 0.5, 0.35, 0, 0],
  },
  received: {
    duration: 1.175,
    peaks: [{at:0.06,level:0.96},{at:0.3,level:0.97},{at:0.6,level:0.98},{at:0.82,level:0.85}],
    level: [0.46, 0.75, 0.92, 0.97, 0.98, 0.83, 0.51, 0.11, 0, 0.32, 0.47, 0.48, 0.54, 0.9, 0.99, 0.96, 0.97, 0.91, 0.8, 0.7, 0.75, 0.74, 0.67, 0.26, 0.05, 0.36, 0.56, 0.77, 0.85, 0.94, 1, 0.98, 0.94, 0.77, 0.65, 0.65, 0.71, 0.72, 0.68, 0.66, 0.86, 0.86, 0.84, 0.8, 0.76, 0.71, 0.7, 0.64, 0.63, 0.56, 0.54, 0.5, 0.44, 0.43, 0.42, 0.26, 0.07, 0, 0],
  },
  check: {
    duration: 1.174,
    peaks: [{at:0.12,level:0.99},{at:0.3,level:0.74},{at:0.54,level:0.96},{at:0.8,level:0.87}],
    level: [0.47, 0.75, 0.8, 0.84, 0.9, 0.97, 1, 0.97, 0.95, 0.87, 0.66, 0.5, 0.45, 0.58, 0.71, 0.76, 0.72, 0.59, 0.15, 0.1, 0.48, 0.75, 0.75, 0.73, 0.73, 0.89, 0.98, 0.97, 0.91, 0.9, 0.87, 0.72, 0.41, 0.17, 0.22, 0.28, 0.38, 0.57, 0.69, 0.89, 0.89, 0.8, 0.83, 0.72, 0.76, 0.65, 0.61, 0.64, 0.53, 0.51, 0.51, 0.42, 0.19, 0.39, 0.49, 0.52, 0.47, 0.15, 0],
  },
};
