/**
 * Typed domain errors. Every failed precondition surfaces as a DomainError with a
 * stable machine-readable code (STATE_MACHINES.md "Failure path").
 */
export type DomainErrorCode =
  | 'INVALID_AMOUNT'
  | 'INVALID_AMOUNT_PRECISION'
  | 'INVALID_RATE'
  | 'CURRENCY_MISMATCH'
  | 'NEGATIVE_AMOUNT'
  | 'UNBALANCED_JOURNAL'
  | 'EMPTY_JOURNAL'
  | 'DUPLICATE_POSTING_KEY'
  | 'JOURNAL_ALREADY_REVERSED'
  | 'REVERSAL_OF_REVERSAL'
  | 'JOURNAL_NOT_FOUND'
  | 'IDEMPOTENCY_KEY_REQUIRED'
  | 'IDEMPOTENCY_KEY_REUSED'
  | 'IDEMPOTENCY_IN_PROGRESS'
  | 'UNAUTHENTICATED'
  | 'FORBIDDEN'
  | 'MFA_ENROLLMENT_REQUIRED'
  | 'MFA_VERIFICATION_REQUIRED'
  | 'STEP_UP_REQUIRED'
  | 'SECOND_APPROVER_REQUIRED'
  | 'SESSION_SURFACE_MISMATCH'
  | 'SESSION_IDLE_TIMEOUT'
  | 'LOCK_ORDER_VIOLATION'
  | 'INVALID_ARGUMENT'
  | 'NOT_FOUND'
  | 'INVALID_TRANSITION'
  | 'STALE_VERSION'
  | 'CLIENT_NOT_ACTIVE'
  | 'DUPLICATE_DESTINATION'
  | 'INVALID_ADDRESS'
  | 'ACCOUNT_NOT_ACTIVE'
  | 'CAPACITY_INSUFFICIENT'
  | 'RESERVATION_NOT_ACTIVE'
  | 'ROUTE_INACTIVE'
  | 'ROUTE_SETTLEMENT_MODEL_UNSUPPORTED'
  | 'ROUTE_DIRECTION_MISMATCH'
  | 'ROUTE_RATE_MISSING'
  | 'WALLET_NOT_ACTIVE'
  | 'RECEIPT_HASH_MISMATCH'
  | 'DUPLICATE_STATEMENT'
  | 'CUSTODY_CAPABILITY_UNSUPPORTED'
  | 'CUSTODY_CAPABILITY_MISMATCH'
  | 'DEPOSIT_ADDRESS_UNAVAILABLE'
  | 'DEPOSIT_ASSIGNMENT_EXISTS'
  | 'RATE_LIMITED'
  | 'REQUEST_NOT_OPEN'
  | 'AMOUNT_ABOVE_LIMIT'
  | 'DIRECTION_DISABLED'
  | 'DESTINATION_INVALID'
  | 'DESTINATION_CHANGED'
  | 'ROUTE_RATE_STALE'
  | 'NEGATIVE_MARGIN_NOT_PERMITTED'
  | 'CONCURRENT_QUOTE'
  | 'QUOTE_NOT_SENT'
  | 'QUOTE_EXPIRED'
  | 'QUOTE_ALREADY_ACCEPTED'
  | 'QUOTE_VALIDITY_INVALID'
  | 'LINK_VALIDITY_TOO_SHORT'
  | 'LINK_NOT_FOUND'
  | 'LINK_EXISTS'
  | 'NOT_AUTHORIZED_TO_ACCEPT'
  | 'KYC_NOT_VERIFIED'
  | 'OTP_INVALID'
  | 'OTP_EXPIRED'
  | 'OTP_ATTEMPTS_EXCEEDED'
  | 'OTP_SEND_LIMIT'
  | 'OTP_RECIPIENT_INVALID'
  | 'TREASURY_INSUFFICIENT'
  // Phase 4 — settlement, route obligations, corrections (STATE_MACHINES §3–§10).
  | 'TRADE_ON_HOLD'
  | 'OVER_ALLOCATION'
  | 'ROUTE_OVER_ALLOCATION'
  | 'ROUTE_PAYER_NOT_ALLOWED'
  | 'ROUTE_NOT_USABLE'
  | 'ROUTE_DIRECT_PAYOUT_MISMATCH'
  | 'ROUTE_OBLIGATION_SETTLED'
  | 'TREASURY_WALLET_NOT_ACTIVE'
  | 'TRANSFER_NOT_CONFIRMED'
  | 'UTR_REQUIRED'
  | 'DUPLICATE_UTR'
  | 'DUPLICATE_TX_HASH'
  | 'FUNDS_ALREADY_RECEIVED'
  | 'PAYOUT_IN_FLIGHT'
  | 'PAYOUT_ALREADY_CONFIRMED'
  | 'REFUND_INCOMPLETE'
  // Phase 5 — chain monitoring (STATE_MACHINES §11).
  | 'CHAIN_PROVIDER_ERROR'
  | 'CHAIN_PROVIDER_DISAGREEMENT'
  | 'CHAIN_MONITORING_UNCONFIGURED'
  | 'INSUFFICIENT_PROVIDER_QUORUM'
  | 'TX_NOT_FINAL'
  | 'TX_ORPHANED'
  | 'SCANNER_CURSOR_CONFLICT';

export class DomainError extends Error {
  readonly code: DomainErrorCode;
  readonly details: Readonly<Record<string, unknown>>;

  constructor(code: DomainErrorCode, message?: string, details: Record<string, unknown> = {}) {
    super(message ?? code);
    this.name = 'DomainError';
    this.code = code;
    this.details = Object.freeze({ ...details });
  }
}

export function isDomainError(err: unknown, code?: DomainErrorCode): err is DomainError {
  return err instanceof DomainError && (code === undefined || err.code === code);
}
