/**
 * Branded identifiers. Ids are UUIDv7 generated by PostgreSQL 18 (`uuidv7()`), so the
 * kernel only validates and brands them.
 */
import { randomBytes } from 'node:crypto';

declare const brand: unique symbol;
export type Id<T extends string> = string & { readonly [brand]: T };

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;

export function isUuid(value: string): boolean {
  return UUID_RE.test(value);
}

export function asId<T extends string>(value: string, _kind: T): Id<T> {
  if (!isUuid(value)) throw new TypeError(`Invalid id: ${value}`);
  return value as Id<T>;
}

let lastMs = 0n;
let seq = 0n;

/**
 * RFC 9562 UUIDv7 for ids created in application code (e.g. by Better Auth's adapter). Monotonic
 * within a process: a 12-bit counter in rand_a breaks ties inside the same millisecond.
 */
export function uuidv7(nowMs: number = Date.now()): string {
  let ms = BigInt(nowMs);
  if (ms <= lastMs) {
    seq++;
    if (seq > 0xfffn) {
      lastMs++;
      seq = 0n;
    }
    ms = lastMs;
  } else {
    lastMs = ms;
    seq = 0n;
  }
  const bytes = randomBytes(16);
  const hex = ms.toString(16).padStart(12, '0');
  for (let i = 0; i < 6; i++) bytes[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  const seqHex = seq.toString(16).padStart(3, '0');
  bytes[6] = 0x70 | parseInt(seqHex.slice(0, 1), 16);
  bytes[7] = parseInt(seqHex.slice(1), 16);
  bytes[8] = (bytes[8]! & 0x3f) | 0x80;
  const h = bytes.toString('hex');
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-${h.slice(12, 16)}-${h.slice(16, 20)}-${h.slice(20)}`;
}
